### ISSUE TITLE
MemberReference fails to resolve when it contains a forwarded type in its signature

### ISSUE THREAD

**Issue by TheProxyRE** [Washi1337/AsmResolver#124]
Sample: dnspy .netcore 64 bit latest
https://github.com/dnSpy/dnSpy/releases/download/v6.1.8/dnSpy-net-win64.zip
File: `dnSpy.dll`

Method:  `0x06000005`  
```csharp
internal sealed class <>f__AnonymousType0<<Path>j__TPar, <Bitness>j__TPar, <Version>j__TPar>
{
       [DebuggerHidden]
	public override bool Equals(object value)
	{
		var <>f__AnonymousType = value as <>f__AnonymousType0<<Path>j__TPar, <Bitness>j__TPar, <Version>j__TPar>;
		return <>f__AnonymousType != null && EqualityComparer<<Path>j__TPar>.Default.Equals(this.<Path>i__Field, <>f__AnonymousType.<Path>i__Field) && EqualityComparer<<Bitness>j__TPar>.Default.Equals(this.<Bitness>i__Field, <>f__AnonymousType.<Bitness>i__Field) && EqualityComparer<<Version>j__TPar>.Default.Equals(this.<Version>i__Field, <>f__AnonymousType.<Version>i__Field);
	}
}
```
```
 IL_000A: call      class [System.Collections]System.Collections.Generic.EqualityComparer`1<!0> class [System.Collections]System.Collections.Generic.EqualityComparer`1<!'<Path>j__TPar'>::get_Default()
 ```
 That member reference fails to resolve.
 
 This is the test code
 ```csharp
[Fact]
public void TestResolve()
{
        var module = ModuleDefinition.FromFile("/home/user/Reversing/dnSpy/bin/dnSpy.dll");
        var method = (MethodDefinition)module.LookupMember(new MetadataToken(0x06000005));
        var operand = (IMethodDescriptor)method.CilMethodBody.Instructions[5].Operand;
        var resolved = operand.Resolve();
        Assert.NotNull(resolved);
}
 ```

**Comment by Washi1337** [comment]
Seems to be an issue that is not exclusive to generic types, but any comparison between `TypeDefOrRef`s that is forwarded by the referenced assembly. The signature comparer does not take into account that forwarded types, such as the one referenced in the sample, has a different `Scope` than the actual `TypeDefinition`. 

This was partially fixed in 46cea9b2e6d6033e3fdde72d264ca25c3c0db75b for type signatures, but adding a similar fix by adding a `Resolve` call in the `Equals` overload is very likely to completely stack overflow, since the metadata resolver uses the signature comparer as well.

If anything, it shows the current implementations of the comparer and resolver are fundamentally flawed. It might be best to just rewrite the entire class, that does take these things into account in a more rigorous manner. This will need some proper design considerations, we do not want to remove `IEqualityComparer` implementations from `SignatureComparer` either.
