### ISSUE TITLE
Platform dependent type memory layout detection

### ISSUE THREAD

**Issue by ElektroKill** [Washi1337/AsmResolver#143]
Hello,
One of the use cases of the type memory calculator feature of AsmResolver is resolving the values pushed by the`sizeof` opcode. Some obfuscators use this opcode in some mathematical expressions to hide the real number. However, when using this feature to inline these instructions a problem arises, some types have a size dependent on the platform the module is run on. This makes it difficult to know if it is safe to inline a sizeof instruction to the computed value for files compiled for AnyCPU.

To solve this I propose a way for the user to know if the result of a type memory layout calculation is platform dependent or not. I don’t really have a good idea on how it could be implemented though.

Thanks in advance!

**Comment by Washi1337** [comment]
How do you envision this exactly?

What happens when the analyzer encounters such a type? Throw an exception? Set a flag? Provide both the 32bits and 64bits sizes instead? Something completely different? Could you perhaps give some pseudo-C# of use-cases of this?

As a workaround, there actually is already some sort of a way to know whether it is platform dependent. You can instruct AsmResolver to compute the memory layout twice, once for the 32bit variant, and the second one with 64bit pointers instead. If it is platform dependent, these sizes will differ.

**Comment by ElektroKill** [comment]
Hello, I don't really have a good idea of how this could be implemented as I am not very familiar with the AsmResolver codebase yet. However, I came up with some potential ways this could be implemented:
* The response of the calculation has a property that specifies if the resulting layout is platform dependant.
* The response contains two possible layouts, one for 32 bit one for 64 bit.
* The `is32Bit` is made nullable and if it is null then an exception is thrown during calculation if something that is platform dependant is encountered.

These are some of the potential ways to implement it I came up with. Basically what I need is a way to tell if the resulting layout is platform dependant without running multiple calculations.

**Comment by Washi1337** [comment]
Probably the first option is the best option. Calculating two possible layouts is not going to be more efficient than just calculating the layout twice with a different bitness specified. And I would rather avoid exceptions that don't really encode the actual inability of calculating the layout (such as the cyclic dependency case).

**Comment by Washi1337** [comment]
Implemented in 2ca613f9ec41c411474330712806a0142d2bb949
