### ISSUE TITLE
AsmResolver fails to serialize image

### ISSUE THREAD

**Issue by chickenienRE** [Washi1337/AsmResolver#184]
## Describe the bug
AsmResolver fails to serialize image to disc. File is attached and is i'm the owner of this file.

## To Reproduce
Load attached binary and then try to serialize the image to disc. I did a little digging and found out that it crashes at Class36 at field serialization. Possibly of the struct stuff.

## Expected behavior
functional image serialization

## Screenshots

![DnSpy](https://user-images.githubusercontent.com/60032424/123280619-39701200-d509-11eb-9108-b907fec0e657.PNG)
![Rider](https://user-images.githubusercontent.com/60032424/123280625-3b39d580-d509-11eb-82ff-27751d775d29.png)

## Platform
 - OS: Windows 10
 - AsmResolver Version: tested on both 4.5.1 and 4.6.0, both fails as well

[Binary.zip](https://github.com/Washi1337/AsmResolver/files/6709990/Binary.zip)

**Comment by Washi1337** [comment]
The binary contains a field with an invalid field RVA, and even with providing an `EmptyErrorListener` to the reader, it still threw an exception instead of recover from the error.

This issue should be fixed on the development branch.

Note: Keep in mind that AsmResolver will only attempt to recover from **reader** errors if you provide the `EmptyErrorListener` upon **reading** a module. Failing to do so will still make AsmResolver throw an exception upon writing. 

Example on how to let AsmResolver attempt to recover from invalid metadata:

```csharp
var readerParameters = new ModuleReaderParameters(EmptyErrorListener.Instance));
var module = ModuleDefinition.FromFile("path/to/file.exe", readerParameters);
```
