### ISSUE TITLE
movzx   ecx, al wrong disassembled

### ISSUE THREAD

**Issue by liiir1985** [Washi1337/AsmResolver#19]
0F B6 C8 is wrongly decoded as:
movzx eax, byte [eax]

but actually it should be:
movzx eax, al

**Comment by Washi1337** [comment]
Hi,

Thanks for the report. Unfortunately, at the moment, the x86 encoder/decoder namespace has very low priority in terms of further development, especially since I started working on AsmResolver v4 (check out the v4 branch for progress).

For the time being, you might be interested in using [Iced](https://github.com/0xd4d/iced/) from 0xd4d instead. It is tested a lot more and supports more features of the x86 instruction set.

Thanks for understanding.

**Comment by liiir1985** [comment]
Thanks for the reply, but unfortunately Iced doesn't suit my requirement, because I also need the ability to load PE files, this is the main reason why I've chosen AsmResolver

Do you have any roadmap regarding the v4 version? what's the difference?

I think I can look into the decoding problem once I got time, and I'll make a PR if I managed to fix the problem

**Comment by Washi1337** [comment]
Version 4 is a complete rewrite of the library, with a much easier and more consistent API. All of the documentation will live in the `docs` folder, or view  https://asmresolver.readthedocs.io/ for an online, rendered version of it. It is still early in development and names of classes and structures are subject to change.

Some good news is that it will still support loading native binaries, and will still expose low level structures as well as high level structures, however I have not yet decided exactly on how to do the native x86 instruction encoding/decoding, if it will be in there at all. Chances are that I will be offloading that to another library, providing the user with the ability to swap out encoders/decoders for different machine languages.

Until v4 is ready to be merged with master, I will still accept PRs for v3, especially since some projects still use it. If you can find the bug in the decoder, I'd be happy to merge your PR for it. The code might actually end up in the newer version as well.
