### ISSUE TITLE
How to modify VersionInfo of a PE file?

### ISSUE THREAD

**Issue by CreateAndInject** [Washi1337/AsmResolver#202]
I'm new user of AsmResolver, can you give me an example on how to modify PE imformation and save it.
```
        void ModifyFileDescription(string input, string output,string newDescription)
        {
            var pe = PEImage.FromFile(input);
            var stringTable = pe.xxx(); // dummy code
            stringTable[StringTable.FileDescriptionKey] = newDescription;
            pe.Write(output); // dummy code
        }
```

**Comment by Washi1337** [comment]
I am assuming you are referring to the version information stored in the win32 resources of the PE. 

You can read, inspect and modify version info using the `VersionInfoResource` class in the `AsmResolver.PE.Win32Resources` package. Unfortunately, documentation for the Win32 resources package is quite lacking, mainly since it is mostly incomplete (see #66). However, you might be able to have a look at how the `VersionInfoResource` class is used by looking at the unit tests for it.

[VersionInfoResourceTest.cs](/Washi1337/AsmResolver/blob/master/test/AsmResolver.PE.Win32Resources.Tests/Version/VersionInfoResourceTest.cs)

As for writing PE image to the disk, this generally goes through an instance of `IPEFileBuilder`. Currently AsmResolver only comes with a PE file builder for .NET images (`ManagedPEFileBuilder`). You can see examples of how to use that class in the wiki https://asmresolver.readthedocs.io/en/latest/peimage/basics.html#writing-a-pe-image. However, if your file is actually a non-.NET image, you would have to write your own "linker" script by implementing `IPEFileBuilder` or deriving from `PEFileBuilderBase`. Unfortunately again the documentation for this part is somewhat lacking, but I do plan on writing more about this in the not-so-distant future.

**Comment by CreateAndInject** [comment]
Thanks, I can do it with .NET now, is it not easy to do it with win32 PE?

**Comment by Washi1337** [comment]
Main problem is that there is not one way to put native images together. .NET images have a far more rigid structure that needs to be adhered to, making a generic  PE file builder for managed applications a lot easier. AsmResolver is slowly moving towards more easier ways to also build native images, but no generic native file builder exists yet.

In your case however, since you're only interested in updating resources, you could open a `PEFile` and replace the contents of the .rsrc section with an instance of a `ResourceDirectoryBuffer` where you add the root resource directory to using the `AddDirectory` method. `PEFile`s can be written to the disk using the `Write` method.

**Comment by CreateAndInject** [comment]
I succeed by the following code:
```
        static void ModifyFileDescription(string input, string output, string newDescription)
        {
            var peImage = PEImage.FromFile(input);
            var versionInfo = VersionInfoResource.FromDirectory(peImage.Resources);
            var stringInfo = versionInfo.GetChild<StringFileInfo>(StringFileInfo.StringFileInfoKey);
            var stringTable = stringInfo.Tables[0];
            stringTable[StringTable.CompanyNameKey] = newDescription;
            versionInfo.WriteToDirectory(peImage.Resources);
            var resourceDirectoryBuffer = new ResourceDirectoryBuffer();
            resourceDirectoryBuffer.AddDirectory(peImage.Resources);
            var peFile = PEFile.FromFile(input);
            peFile.Sections.First(x => x.Name == ".rsrc").Contents = resourceDirectoryBuffer;
            peFile.Write(output);
        }
```

But there's 2 problems:
1. I can't get root resource directory from PEFile, so I read file twice(PEImage.FromFile+PEFile.FromFile)
2. I think `peFile.Sections.First(x => x.Name == ".rsrc")` isn't credible, but I don't know how to get the section of peImage.Resources

**Comment by Washi1337** [comment]
1. You only have to read the file once. You can use the `PEImage.FromFile` to open an image from an existing `PEFile` as well.
   ```csharp
   var file = PEFile.FromFile(@"C:\MyFile.exe");
   var image = PEImage.FromFile(file);
   ```

2. This is true, and here in lies also the core problem with making a generic builder for arbitrary `PEImage`s. You can find out which section the resources directory is located in by checking the data directories stored in the optional header:
   ```csharp
   var file = PEFile.FromFile(@"C:\MyFile.exe");
   var directory = file.OptionalHeader.DataDirectories[(int) DataDirectoryIndex.ResourceDirectory];
   if (directory.IsPresentInPE)
   {
      var section = file.GetSectionContainingRva(directory.Rva);
      // ...
   }
   ```

**Comment by CreateAndInject** [comment]
>    ```cs
>    var file = PEFile.FromFile(@"C:\MyFile.exe");
>    var directory = file.OptionalHeader.DataDirectories[(int) DataDirectoryIndex.ResourceDirectory];
>    if (directory.IsPresentInPE)
>    {
>       var section = file.GetSectionContainingRva(directory.Rva);
>       // ...
>    }
>    ```

There's a minor error, `DataDirectory` doesn't contain a member named `Rva`, I think it's `VirtualAddress`
`file.GetSectionContainingRva(directory.Rva) => file.GetSectionContainingRva(directory.VirtualAddress)`

Thanks!

**Comment by Washi1337** [comment]
Yes my bad, you are absolutely correct. I probably should not try to code inside GitHub's markdown editor without a proper linter :)

**Comment by jwfx** [comment]
@Washi1337 @CreateAndInject 

I tried to follow this solution, but I ended up with a broken VERSIONINFO.

The language ID is gone, the VERSIONINFO is incomplete (VarFileInfo block is missing and also the closing brace) and it seems like the section is serialized incomplete because the following Manifest resource is missing the starting XML tag.

Any idea what I could be doing wrong? 

Resource Hacker screenshots:

**Unchanged:**
![image](https://github.com/Washi1337/AsmResolver/assets/39484381/0d87700b-3070-43d6-8c1f-66ce444fc3b1)

**Modified:**
![image](https://github.com/Washi1337/AsmResolver/assets/39484381/00887588-466d-44f1-b9c7-17240daa3611)

**Comment by Washi1337** [comment]
@jwfx I think the problem may be on your end. The following code works fine on my end with a simple `HelloWorld.exe`:

```csharp
// Open PE file, and then as image.
var file = PEFile.FromFile(@"C:\Path\To\Executable.exe");
var image = PEImage.FromFile(file);

// Open version info from the PE's resources:
var versionInfo = VersionInfoResource.FromDirectory(image.Resources!)!;

// Update the file description to something.
var info = versionInfo.GetChild<StringFileInfo>(StringFileInfo.StringFileInfoKey);
info.Tables[0][StringTable.FileDescriptionKey] = "This is a test application";

// Write version info back into resources directory.
versionInfo.WriteToDirectory(image.Resources!);

// We need to rebuild the resources section, let's create a new buffer and add the directory.
var resourceBuffer = new ResourceDirectoryBuffer();
resourceBuffer.AddDirectory(image.Resources!);

// Obtain the original resource section, and replace its contents.
var section = file.GetSectionContainingRva(file.OptionalHeader.GetDataDirectory(DataDirectoryIndex.ResourceDirectory).VirtualAddress);
section.Contents = resourceBuffer;

// Update offsets and sizes.
file.UpdateHeaders();
file.OptionalHeader.SetDataDirectory(DataDirectoryIndex.ResourceDirectory,
    new DataDirectory(resourceBuffer.Rva, resourceBuffer.GetPhysicalSize()));

// Write to disk.
file.Write(@"C:\Path\To\Executable.patched.exe");
```

**Comment by jwfx** [comment]
@Washi1337 

Thanks for your updated example.

I was hoping the `UpdateHeaders()` part would solve my problem, as I was missing that. Unfortunately your updated example produces the same issue as before.

I've uploaded the unmodified .exe in question here https://github.com/jwfx/VersionTest

For reference, this is just the resulting installer .exe from an Inno Setup example build, see [here](https://github.com/jrsoftware/issrc/blob/main/Examples/Example1.iss)
They do have a bit weird things going on with trailing whitespaces, but I think that shouldn't be a problem.

**Comment by Washi1337** [comment]
@jwfx Thanks for the test file. I indeed have identified that there is a bug with the writing process of the `VersionInfoResource` lcass. I have found a fix which I will upload shortly. Would you mind if I use your executable as part of one of the unit tests?

**Comment by jwfx** [comment]
@Washi1337 I wouldn't mind at all. The executable is completely generic since it is just one of the Inno Setup examples.

Just for future reference: Download and install InnoSetup, load the Example1.iss, hit compile this executable should show up in the "%userprofile%\Documents\Inno Setup Examples Output" folder

Really appreciate your quick response and efforts.

**Comment by jwfx** [comment]
I tested it and it does indeed solve the issue - Thanks for that.

The language of the resource is not preserved with the example code. Checking with Resource Hacker it still looks like in my screenshots above (left panel, highlighted in blue).

Does it require additional code to carry it over?

**Comment by Washi1337** [comment]
@jwfx  This is a very good point, and I believe you found another oversight of my understanding of the Win32 resource format :).

I propose we extend the `VersionInfoResource.FromDirectory` with an extra parameter to get language specific version info, such that we can provide `VersionInfoResource` with the right language ID, and thus have `WriteToDirectory` assign the right language ID as well when constructing new resource data entries. We also may want to have another factory method that obtains *all* version info entries present in the file, 

Regardless, this will likely be part of a separate issue/PR. For now, I think I will just default the value to 1033 (English - United States), since this seems to be the most commonly used value anyways.
