### ISSUE TITLE
Malicious TypeSpec loop causes AsmResolver to completely hang and crash

### ISSUE THREAD

**Issue by XenocodeRCE** [Washi1337/AsmResolver#22]
Following this : https://github.com/0xd4d/dnlib/issues/331

I tired with DotNetResolver 3.3.0.0 (i know, old release) but i couln't prevent any crashes.

actually kinda all decompilers, even those based on mono cecil, crashes

only http://www.netdecompiler.com/index.html doesn't crash but its too old and doesn't give that much information

**Comment by Washi1337** [comment]
Older versions of AsmResolver are not really supported anyone. DotNet Resolver iirc uses v1 or v2. Both haven't been updated for a few years already.

In version 3 the bug was fixed.

Version 4 is being developed at branch v4 which doesn't have the bug either. This is actually how I found the bug in dnSpy, by crafting a malicious signature using AsmResolver 4.
