### ISSUE TITLE
LoopContinue and others

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#27]
Does AsmResolver Contains CilCode like: LoopContinue,YieldBreak,.. as in ILSpy? and Why?

**Comment by Washi1337** [comment]
`LoopContinue` and `YieldBreak` are not opcodes found in the CIL instruction set. These instructions can be found in ILSpy's instruction model because ILSpy uses their own intermediate representation that is an extension on the normal CIL. From my understanding, they transform certain normal CIL constructions into these pseudo opcodes to simplify the decompilation process.

You will not find these operation codes in AsmResolver, nor in any other library (Cecil, dnlib, System.Reflection, System.Reflection.Metadata, etc.) that only implements the CIL instruction set architecture.
