### ISSUE TITLE
Importing a nested type loses declaring type information

### ISSUE THREAD

**Issue by SamboyCoding** [Washi1337/AsmResolver#273]
## Describe the bug
Calling ReferenceImporter::ImportType on a type definition with a DeclaringType set results in a TypeReference with the resolution scope set to the module, not to the declaring type, so the TypeReference does not inherit the declaring type and an invalid type reference is emitted to the assembly.

## To Reproduce
1. Set the base type of an type to be an imported reference to a nested type in another assembly
2. Attempt to open the type in ILSpy
3. ILSpy throws an exception (at least in C# mode, IL mode is fine)

## Expected behavior
The type can be loaded successfully by ILSpy or Mono.Cecil, or indeed AsmResolver, and its base type can be resolved.

## Screenshots
(Excuse the obfuscation)

ILSpy isn't loading these nested types because they have unresolvable base types
![image](https://user-images.githubusercontent.com/7011721/158859534-3f7ce0ba-1839-4370-973c-5cd0281e82f5.png)
You can see the type is nested (hence the +) but it's being imported with the scope = module
![image](https://user-images.githubusercontent.com/7011721/158859781-d2a4f090-d2c1-40ee-b0cd-fb96b7ec269b.png)
Resulting type reference with no declaring type and scope = assembly reference.
![image](https://user-images.githubusercontent.com/7011721/158859938-dd1d6e05-7c38-4aed-8166-0f88b39c2aa5.png)

## Platform
 - OS: Windows 11
 - AsmResolver Version: 4.9.0

**Additional context**
N/A

**Comment by SamboyCoding** [comment]
I should add that the net result of this is that, when trying to resolve the type using e.g. Cecil, it looks for a *top-level* type with the name of the nested type, which obviously doesn't exist.

**Comment by SamboyCoding** [comment]
Testing now

**Comment by SamboyCoding** [comment]
Yes I can confirm this fixes the issue. Thanks for the quick turnaround!

**Comment by SamboyCoding** [comment]
Any chance this could possibly become a 4.9.1 bugfix release? It's kind of a major blocker for a release I was hoping to get out today.

**Comment by Washi1337** [comment]
I typically only reserve hotfixes for critical bugs that were introduced by changes in the previous release. I wouldn't classify this issue as one; it hasn't been reported until now despite being present since probably the beginning of 4.0.0, and it can be relatively easily worked around.

I also typically don't try to merge my own PRs until I looked over the code at least one more time with a fresh pair of eyes (typically with at least a night sleep in between). As you have seen with this issue, while there are many unit tests in AsmResolver, they unfortunately still do not cover every use case there is.

Besides, I have a feeling you will be finding more ~~bugs~~ hidden features relatively soon anyways, which we may be able to batch into the same release ;)

**Comment by SamboyCoding** [comment]
Well I can at least confirm that with the combination of all the fixes you've done so wonderfully over the last day-and-a-half, I'm getting the same output now as I was under cecil - or at least close enough that downstream tools don't pick up any difference - so I'm not expecting to find any more 'hidden features' in the next few days. We'll see how that opinion changes once I start actually populating method bodies haha (though I don't expect this to be for several weeks at the very least, yet)
