### ISSUE TITLE
Possible Naming Inconsistency

### ISSUE THREAD

**Issue by ds5678** [Washi1337/AsmResolver#276]
I found 

`AsmResolver.DotNet.Signatures.CallingConventionAttributes.C`

which I think should be:

`AsmResolver.DotNet.Signatures.CallingConventionAttributes.Cdecl`

Was this intentional or just an accident?

**Comment by Washi1337** [comment]
This is intentional. The [ECMA-335](https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf) (II.23.2.3), as well as [src/coreclr/inc/corhdr.h](https://github.com/dotnet/runtime/blob/c5d40c9e703fd257db1b26ef4fd1399bbae73ab0/src/coreclr/inc/corhdr.h#L970) defines this calling convention as `C` instead of `Cdecl`.
