### ISSUE TITLE
[Feature Request]: Deep Cloning

### ISSUE THREAD

**Issue by ds5678** [Washi1337/AsmResolver#281]
## Problem Description
It would be convenient to duplicate entire `AssemblyDefinition` objects. This would allow modification of duplicates without affecting the originals, particularly in instances when `AssemblyDefinition` are received as output from another library using AsmResolver. However, I understand this is a tall order and may be infeasible.

Related: #93

## Proposal
Since multiple assemblies could be cloned at once, an `AssemblyCloner` class would probably be ideal.

## Alternatives
It should be possible to write the assemblies and read them, but this is probably more computationally intensive. It also only works if the originals have no write issues, though I'm not worried about this. 

It might be possible to manually recreate copies using the member cloning system, though this may require support for custom reference importers.

## Additional context
In my case, the library I mentioned earlier is @SamboyCoding's [Cpp2IL](https://github.com/SamboyCoding/Cpp2IL). It outputs reconstructed Unity assemblies to which I want to apply multiple sets of stripping, including one set where I don't strip at all.

**Comment by JPaja** [comment]
You can technically do this already. What you have to do is create new assembly or module definition and import all cloned members there, but issue is all member references would still point to original module, so you have to find all members that contains TypeReference/MemberReference/ModuleReference (eg instruction operands, type base types, type specifications, etc..) and fix them yourself.

Currently you can look at Workspaces code to find all paths to member/type/module references. Workspaces can get all member references within multiple assemblies but sadly it is not yet convenient for this task due to not having relations that point to what metadata member used that reference (eg you cannot know if member reference was instanced from instruction operand or base type) because you have to replace that member with new fixed reference.
