### ISSUE TITLE
Problem on recompiling

### ISSUE THREAD

**Issue by SirDeveloperOrg** [Washi1337/AsmResolver#295]
Hi, first of all I want to thank you for your great works.
I have a problem on recompiling devirtualized methods, i get few errors when I trying to save PEImage.

![image](https://user-images.githubusercontent.com/93499598/162982148-2a8e7f70-dc97-4770-8e18-27f2fc182142.png)

But the devirtualized method body looks OK:

![image](https://user-images.githubusercontent.com/93499598/162982329-a7d26081-e53e-40ea-96b7-c427a6350bd0.png)

![image](https://user-images.githubusercontent.com/93499598/162982369-7b19fcd5-5f2b-4472-9a88-d2bd7f639aae.png)

And this is the original method body in original (no vm) file:

![image](https://user-images.githubusercontent.com/93499598/162983035-94053887-26cd-467d-ac04-7831ac26abfa.png)

![image](https://user-images.githubusercontent.com/93499598/162983109-d0737f80-7fb1-436a-ab2d-6d550332a6e4.png)

I'm not sure but I guess one of errors is about the way I branching instructions because it's working fine when method body does not contains any branch instruction, and another errors is about method body locals. (Just guess, Not sure)

``` c#
method.CilMethodBody.Instructions[i] = new CilInstruction(CilOpCodes.Brfalse,
method.CilMethodBody.Instructions[/*<INDEX>*/].CreateLabel()) 
{
    /* It's prevent instruction offset being changed while I recompiling devirtualized & deassembled methods */
    Offset = method.CilMethodBody.Instructions[i].Offset
};

method.CilMethodBody.Instructions[x] = new CilInstruction(CilOpCodes.Br,
method.CilMethodBody.Instructions[/*<INDEX>*/].CreateLabel()) 
{
    /* It's prevent instruction offset being changed while I recompiling devirtualized & deassembled methods */
    Offset = method.CilMethodBody.Instructions[x].Offset
};
```

I'll be appreciated if you could guide me.

REGARDS.

**Comment by Washi1337** [comment]
First, can you tell me which version of AsmResolver you used?

The errors indicate that you are passing in the wrong _types_ of operands into your `CilInstruction`s. Please refer to [Basic structure of CIL instructions](https://asmresolver.readthedocs.io/en/latest/dotnet/managed-method-bodies.html#basic-structure-of-cil-instructions) in the documentation for an overview of what is expected to be in the operand for every type of opcode.

For your specific case: the first error indicates the label that you are using in your branch instruction is invalid. Make sure that your instructions reference labels that are within the method body. If you are using `instruction.CreateLabel()`, ensure that `instruction` is (still) part of the same method body as well upon writing the assembly. Have a look at [Branching Instructions](https://asmresolver.readthedocs.io/en/latest/dotnet/managed-method-bodies.html#branching-instructions) for an example for creating branch instructions.

For the other two errors, these are indeed indications that your local variable references in the operands are incorrect. As the table in the documentation describes, the operand for these types of instructions should either be a `byte` or `ushort` (depending on whether you use the short or long version of the opcode), or a `CilLocalVariable` that is present in the same method body. If either of these is not met, AsmResolver will throw an exception like the ones you are seeing right now.

I am unsure what the purpose is of setting `Offset` in your code snippet. You might also want to try to use the overloaded `Add` or `ReplaceWith` methods that take an opcode and operand directly, rather than creating the `CilInstruction` objects yourself. These methods do validation on your opcodes and operands before they are added to the list, which may help you figuring out what you might have done wrong.

**Comment by SirDeveloperOrg** [comment]
this is how I add local variables:

``` c#
foreach (var local in LocalsList)
{
    /* local is a ITypeDescriptor */
    method.Parent.CilMethodBody.LocalVariables.Add(new CilLocalVariable(local.Resolve().ToTypeSignature()));
}
```

As you said I tried ReplaceWith but still I get same errors.

Can I contact you privately to send you my devirtualizer source code?
I'll be appreciated if you could spend few minutes to check it.

**Comment by SirDeveloperOrg** [comment]
I sent a friend request to you on Discord, Please accept it.
My name in Discord: Ophelia

**Comment by Washi1337** [comment]
Your snippet for adding the local variables looks fine, but the problem is not there but in the way you use the local variables in your instructions' operands. You would need to show how exactly you're adding instructions to your method bodies, and where you are pulling the operands from.

As for Discord, see #291

**Comment by SirDeveloperOrg** [comment]
Problem fixed, thanks to @Washi1337 for guiding me ❤️.
