### ISSUE TITLE
ThisParameter

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#30]
How to find out if ThisParameter is In (Ref read only) parameter from Method Definition?

**Comment by Washi1337** [comment]
Hi,

In parameters are parameters passed on by reference, and have the In flag set. Something int he lines of the following can check these properties:

```csharp
int index = ...;
bool isIn = (method.Parameters[index].Attributes & ParameterAttributes.In) != 0;

if (method.Signature.HasThis)
   index--;
bool isByRef = method.Signature.Parameters[index].ParameterType is ByReferenceSignature;
```

As far as I know, a this parameter never has a dedicated row in the Param table. That is, it is never assigned a ParameterDefinition. Maybe I am wrong though. Can you provide me with an example of when a this parameter is declared ref readonly?

Regards

**Comment by dashne** [comment]
I saw that in ILSpy 6 (preview Version), in ILReader class,in InitParameterVariables() function:
`ILVariable ilVar2 = CreateILVariable(-1, declaringType, "this");
			ilVar2.IsRefReadOnly = method.ThisIsRefReadOnly;
			parameterVariables[paramIndex++] = ilVar2;`
You can see the rest of code your self,I was also stunned when I saw that , why should ThisParameter needs to be [In]!

**Comment by Washi1337** [comment]
Did some digging, here are the specifics:
- This parameters are always passed on by reference, so its type is either going to be a type signature with `IsValueType` set to `true`, or it is going to be a `ByReferenceTypeSignature`.
- The this parameter is also considered read-only when the enclosing type is also marked as readonly. This happens when the `System.Runtime.CompilerServices.IsReadOnlyAttribute` attribute is assigned to the type. This can easily be checked in AsmResolver by simply iterating over all custom attributes of the declaring type and see if there exists any custom attribute with this exact name.

Sources:
-  [MetadataMethod.cs line 429](https://github.com/icsharpcode/ILSpy/blob/8f90f3834dfec079ecbd4345ad6a75acc3145973/ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataMethod.cs#L429)
-  [MetadataTypeDefinition.cs line 110](https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataTypeDefinition.cs#L110)

**Comment by dashne** [comment]
what a bout `IsReadonly`  member of `DeclareType ` ( `ITYpeDefOrRef` ), is that the same of attribute of
`System.Runtime.CompilerServices.IsReadOnlyAttribute` ?, I thought its the same.

**Comment by Washi1337** [comment]
`IsReadOnly` refers to whether the AsmResolver MetadataMember object itself is read only, not to the IsReadOnly attribute that might be assigned to the member or not. This ties within the locking/unlocking system of AsmResolver v3.

**Comment by dashne** [comment]
Custom Attributes are `FixedArgument ` and `NamedArgument` ,which one could be the Attribute: `System.Runtime.CompilerServices.IsReadOnlyAttribute` ?

**Comment by Washi1337** [comment]
Neither. `FixedArguments` and `NamedArguments` are part of the custom attribute's instantiation signature. They determine what arguments are passed onto the constructor of the attribute.
What you're looking for is the `DeclaringType` of the `Constructor` property of `CustomAttribute`.

**Comment by dashne** [comment]
Please,could you provide a sample code How to do that If I have a `MethodDefinition`

**Comment by Washi1337** [comment]
Something in the lines of the following should work:

```csharp
const string isReadOnlyAttributeName = "System.Runtime.CompilerServices.IsReadOnlyAttribute";

MethodDefinition method = ...
var declaringType = method.DeclaringType;

bool hasReadOnlyAttribute = declaringType.CustomAttributes.Any(c => c.Constructor.DeclaringType.FullName == isReadOnlyAttributeName);
```

**Comment by dashne** [comment]
Thank You
