### ISSUE TITLE
Adding multiple members to a TypeDefinition with AddRange()

### ISSUE THREAD

**Issue by 766F6964** [Washi1337/AsmResolver#38]
Currently, adding members like _EventDefinitons_, _FieldDefinitions_ and _MethodDefinitions_  to a _TypeDefiniton_ is done with the _Add()_ method.

However, sometimes it is required to add multiple members at once. 
Right now, the only solution is to write a loop that iterates over all members in a given collection and  performs the _Add()_ operation on each one.

For convenience, I propose adding a _AddRange(IEnumerable\<T\>)_ method.
That way adding many members at once does not require the user to write a loop every time.

**Comment by 766F6964** [comment]
Same also applies for the _ModuleDefinition_ class and adding _TopLevelTypes_.

**Comment by Washi1337** [comment]
I can see how it could potentially improve readability. But, this suggestion comes with a few complications:

- Classes such as `TypeDefinition` expose their members as an `IList<T>` rather than their concrete implementation. `IList<T>` doesn't define an `AddRange` method, because `AddRange` is specific to `List<T>` only.

- The actual lists that represent the members defined in a `TypeDefinition` are not just normal `List<T>` objects. Rather, they are special lists that support lazy initialization and do additional logic next to just adding and removing items (such as verifying and assigning the `DeclaringType` property for a method or field). Adding an AddRange method has a few performance issues, which may or may not be an issue:
   - The benefit of `List<T>.AddRange` is that it is faster for some `IEnumerable<T>`s because sometimes iterating over the collection can be avoided. This is not possible using the member collections, because properties like `DeclaringType` have to be updated upon adding an item.
   - What should `AddRange` do if at least one member was already added to another `TypeDefinition`? As of right now, these member lists throw an exception if you try an item that was already added to another type. If `AddRange` were to be added, it should have the same all-or-nothing approach. This would mean `AddRange` would have to iterate over the collection a second time.

- A solution would be to expose `LazyList<T>` (or even `OwnedCollection<TOwner, TItem>`) directly, but that would break modularity and increase class coupling. Some implementations of classes such as `TypeDefinition` might use different back-end implementations for its collections (e.g. one might use lazy loading). 

- Another solution for this is to let AsmResolver define their own set of extension methods to `IList<T>`, including an `AddRange`. However, since `IList<T>` is part of .NET standard, it could introduce ambiguity for other developers that might have defined similar extensions with the same name.

**Comment by Washi1337** [comment]
Partially implemented in `LazyList`. Design choice was made to not promote list properties from `IList<T>` to `LazyList<T>` for modularity purposes. It would also be a breaking change.
